### ISSUE TITLE
[BUG] Crashes on dedicated server

### ISSUE THREAD

**Issue by technobaboo** [Virus5600/Defensive-Measures-Mod#3]
When run on a dedicated server, client-specific code (https://github.com/Virus5600/Defensive-Measures-Mod/blob/main/src/main/java/com/virus5600/DefensiveMeasures/entity/ModEntities.java#L80) is run causing it to crash.

### **To Reproduce**
Just run it on a dedicated server

[latest.log](https://github.com/Virus5600/Defensive-Measures-Mod/files/10415536/latest.log)

**Comment by Virus5600** [comment]
It's because of compatibility issues with Quilt. Apparently, the code used a Fabric exclusive code that caused compatibility with Quilt resulting to a crash. Sorry but there's currently no plan to port the mod from Fabric to Quilt.

**Comment by Virus5600** [comment]
Re-opening due to a duplicate bug from a fabric loader. I apologize for assuming this was a compatibility issue with quilt. I'll do my best to fix this one as well.

**Comment by Virus5600** [comment]
Hello, you can now download the updated version here:
https://www.curseforge.com/minecraft/mc-mods/defensive-measures/files/4372197
