### ISSUE TITLE
Mod more fits the category of "Client and server" instead of "Client" on Modrinth.

### ISSUE THREAD

**Issue by Caketaco** [Virus5600/Defensive-Measures-Mod#7]
This mod requires both the client and server to have it installed for it to work. 

The "Client" label is for mods you can use on servers regardless of if they have it installed or not.

Also-- absolutely love the textures and models for this mod. Talented stuff!

**Comment by Virus5600** [comment]
Oh, thank you very much for clarifying it! I'm really new to this community and still learning the ropes so I appreciate it a lot!
